name: bdtools

channels:
  - conda-forge

dependencies:
  # conda-core
  - python=3.10
  - numpy=1.24*
  - numba
  - scipy
  - pandas
  - scikit-image
  - opencv
  - scikit-learn
  - joblib
  - matplotlib-base
  - pip
  # conda-spec
  - pytest
  - napari
  - pyqt
  - spyder
  # conda_tf-nogpu
  - pip:
    # pip-core
    # pip-spec
    # pip_tf-nogpu
    - albumentations
    - segmentation-models
    - tensorflow==2.10