name: bdtools

channels:
  - conda-forge
      
dependencies:
  - python=3.11
  - numpy=1.24.*
  - scipy
  - scikit-image
  - joblib
  - numba
  - pytest
  - spyder
  - pip
  - pip:
      - setuptools>=58.0.0
      - wheel
      - twine
